const products = [
  {
    id: 1,
    image: "/assets/wireless-headphones.jpg",
    name: "Wireless Headphones",
    price: "₹6499",
    rating: 4.5,
  },
  {
    id: 2,
    image: "/assets/smartwatch.jpg",
    name: "Smart Watch Series 5",
    price: "₹1299",
    rating: 4.3,
  },
  {
    id: 3,
    image: "/assets/bluetooth-speaker.jpg",
    name: "Portable Bluetooth Speaker",
    price: "₹2599",
    rating: 4.6,
  },
  {
    id: 4,
    image: "/assets/laptop-backpack.jpg",
    name: "Laptop Backpack",
    price: "₹2499",
    rating: 4.4,
  },
  {
    id: 5,
    image: "/assets/gaming-mouse.jpg",
    name: "Gaming Mouse",
    price: "₹899",
    rating: 4.7,
  },
  {
    id: 6,
    image: "/assets/fitness-tracker.jpg",
    name: "Fitness Tracker",
    price: "₹999",
    rating: 4.2,
  },
  {
    id: 7,
    image: "/assets/dslr-camera.jpg",
    name: "DSLR Camera",
    price: "₹29999",
    rating: 4.8,
  },
  {
    id: 8,
    image: "/assets/phone-stand.jpg",
    name: "Adjustable Phone Stand",
    price: "₹499",
    rating: 4.1,
  },
  {
    id: 9,
    image: "/assets/tablet.jpg",
    name: "10-inch Android Tablet",
    price: "₹15999",
    rating: 4.4,
  },
  {
    id: 10,
    image: "/assets/usb-c-hub.jpg",
    name: "USB-C Multiport Hub",
    price: "₹999",
    rating: 4.5,
  },
  {
    id: 11,
    image: "/assets/wireless-keyboard.jpg",
    name: "Wireless Keyboard",
    price: "₹799",
    rating: 4.3,
  },
  {
    id: 12,
    image: "/assets/office-chair.jpg",
    name: "Ergonomic Office Chair",
    price: "₹1999",
    rating: 4.6,
  },
  {
    id: 13,
    image: "/assets/power-bank.jpg",
    name: "Power Bank (20000mAh)",
    price: "₹1499",
    rating: 4.4,
  },
  {
    id: 14,
    image: "/assets/noise-cancelling-earbuds.jpg",
    name: "Noise Cancelling Earbuds",
    price: "₹2999",
    rating: 4.5,
  },
  {
    id: 15,
    image: "/assets/curved-monitor.jpg",
    name: "Curved 4K Monitor",
    price: "₹12999",
    rating: 4.7,
  },
];

export default products;
